version: '3.1'
services:
    mysql:
        container_name: mysql_wunder_mobility
        platform: linux/x86_64
        image: mysql:5.7
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=secret
            - MYSQL_DATABASE=wundermobility
            - MYSQL_USER=wundermobility
            - MYSQL_PASSWORD=secret
        ports:
            - '3306:3306'

    webserver:
        container_name: webserver_wunder_mobility
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '25000:80'

    php-fpm:
        container_name: php_wunder_mobility
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'